name: amazon

channels:
  - conda-forge

dependencies:
  - beautifulsoup4 == 4.11.1
  - flake8
  - jupyter == 1.0.0
  - jupyterlab == 3.4.3
  - matplotlib == 3.5.2
  - nltk == 3.6.7
  - numpy == 1.22.4
  - pandas == 1.4.2
  - python>=3.9
  - scikit-learn == 1.1.1
  - urllib3 == 1.26.9
